### ISSUE TITLE
push_matrix() and pop_matrix() not working

### ISSUE THREAD

**Issue by tyagi619** [p5py/p5#156] opened 2020-04-18 17:24 UTC
using pop_matrix() does not restore the transform matrix to the previous state. I tried using the exact codes mentioned in your documentation : https://p5.readthedocs.io/_/downloads/en/latest/pdf/. 

from p5 import *
def setup():
    size(200, 200)
def draw():
    background(255)
    fill(192)
    no_stroke()
    rect((40, 40), 40, 40)
    push_matrix()
    translate(40, 40)
    rotate(radians(45))
    fill(0)
    rect((40, 40), 40, 40)
    pop_matrix()
if __name__ == '__main__':
    run()

The following code clearly depicts the error

**Comment by tyagi619** [comment] 2020-04-18 18:29
I have figured out a solution for the problem, which i would like to discuss. Using when pop_matrix() is called, it calls push_matrix(), which is decorated by  @contextmanager. The issue is, this results in previous_matrix being updated to the current state of transform_matrix, and losing all information about the transfor_matrix when it was called. Instead, we can have an attribute to Renderer class named prev_transform_matrix, which will store the previous state when push_matrix is called, and will update the transform matrix to prev_transform_matrix, when pop_matrix() is called. This method has solved the problem but it isn't updated in the github repo.

**Comment by tyagi619** [comment] 2020-04-18 18:32
I have figured out a solution for the problem, which i would like to discuss. Using when pop_matrix() is called, it calls push_matrix(), which is decorated by @contextmanager. The issue is, this results in previous_matrix being updated to the current state of transform_matrix, and losing all information about the transfor_matrix when it was called. Instead, we can have an attribute to Renderer class named prev_transform_matrix, which will store the previous state when push_matrix is called, and will update the transform matrix to prev_transform_matrix, when pop_matrix() is called. This method has solved the problem but it isn't updated in the github repo.

**Comment by jeremydouglass** [comment] 2020-04-18 20:23
> The following code clearly depicts the error

I can't reproduce this. When I run the above code, with proper indenting, and with a correct `__name__`, like this:

```
from p5 import *

def setup():
  size(200, 200)
  
def draw():
  background(255)
  fill(192)
  no_stroke()
  rect((40, 40), 40, 40)
  push_matrix()
  translate(40, 40)
  rotate(radians(45))
  fill(0)
  rect((40, 40), 40, 40)
  pop_matrix()

if __name__ == '__main__':
    run()
```

I get:

<img width="200" alt="Screen Shot 2020-04-18 at 1 21 02 PM" src="https://user-images.githubusercontent.com/798570/79670398-7b6c2e00-8177-11ea-861a-f780e90afb83.png">

That is correct (equivalent to output it Processing, Processing.py, et cetera)

**Comment by tyagi619** [comment] 2020-04-19 07:12
I kind of made a mistake while copying the code. Here is the code:
`from p5 import *`
`def setup():`
`    size(200, 200)`
`def draw():`
`    background(255)`
`   fill(192)`
`    rect((40, 40), 40, 40)`
`    push_matrix()`
`    translate(40, 40)`
`    rotate(radians(45))`
`    fill(0,255,0,128)`
`    rect((0, 0), 40, 40)`
`    pop_matrix()`
`    rect((0, 0), 40, 40)`
`if __name__ == '__main__':`
`    run()`
This is the output in p5:
![Screenshot from 2020-04-19 12-18-56](https://user-images.githubusercontent.com/35839837/79681836-019d7880-823b-11ea-93bb-84069a9b397d.png)

This is the output in processing, processing.py:
![Screenshot from 2020-04-19 12-18-44](https://user-images.githubusercontent.com/35839837/79681842-1f6add80-823b-11ea-8a9f-da37d042d987.png)

**Comment by jeremydouglass** [comment] 2020-04-19 15:25
Format you code by highlighting it and pressing `<>` button. This puts three ` above and below.

I can reproduce a problem with `pop_matrix()` like this.

```
from p5 import *

def setup():
  size(200, 200)

def draw():
  background(255)
  translate(40, 40)
  
  fill(0)
  rect((0, 0), 80, 40)
  
  # translate and rotate
  push_matrix()
  translate(40, 40)
  rotate(radians(45))
  fill(128)
  rect((0, 0), 80, 30)
  pop_matrix()
  
  # red shape should be on first
  # at 40,40
  # but is on second
  # at 80,80 r45
  fill(255,0,0)
  rect((0, 0), 80, 20)
  
if __name__ == '__main__':
  run()
```

<img width="200" alt="Screen Shot 2020-04-19 at 8 24 05 AM" src="https://user-images.githubusercontent.com/798570/79691955-3d264b80-8217-11ea-9275-764d1aa9d36d.png">

**Comment by tyagi619** [comment] 2020-04-19 16:16
Can you share the result for your code in processing?

**Comment by jeremydouglass** [comment] 2020-04-19 17:40
Sure, but then we should move this discussion to the forum:

https://discourse.processing.org

GitHub issues aren't the best place for coding help discussions.

The changes to make are:

1. delete import
2. delete `if __name__`
3. change (x, y) tuples to separate arguments: `rect(40, 40, 40, 40)`

```
def setup():
  size(200, 200)

def draw():
  background(255)
  fill(192)
  rect(40, 40, 40, 40)
  pushMatrix()
  translate(40, 40)
  rotate(radians(45))
  fill(0,255,0,128)
  rect(0, 0, 40, 40)
  popMatrix()
  rect(0, 0, 40, 40)
```

As you can see, the third rect is green. In your drawing it is gray. I'm not sure what you did.

<img width="200" alt="Screen Shot 2020-04-19 at 10 37 37 AM" src="https://user-images.githubusercontent.com/798570/79695137-dfe7c580-8229-11ea-93c9-d6d74e5d99f8.png">

If you want to write idiomatic processing.py, you can also make pushMatrix() a self-closing context manager using `with` and dropping `popMatrix()` like this:

```
def setup():
  size(200, 200)

def draw():
  background(255)
  fill(192)
  rect(40, 40, 40, 40)
  with pushMatrix():
    translate(40, 40)
    rotate(radians(45))
    fill(0,255,0,128)
    rect(0, 0, 40, 40)
  rect(0, 0, 40, 40)
```

This produces the same image output as above.

**Comment by tyagi619** [comment] 2020-04-19 17:49
As far as the issue is concerned, using 
```
with push_matrix():
        ....Some Code.....
```
does solve the issue

**Comment by jeremydouglass** [comment] 2020-04-19 19:53
> does solve the issue

Huh. It produces correct behavior, yes.

But the issue you found is pop_matrix() not working -- it doesn't solve that issue.

**Comment by jeremydouglass** [comment] 2020-04-19 20:50
Hmm. Looking at the documentation here: https://github.com/p5py/p5/blame/master/docs/guides/for-processing-users.rst

> * Processing's :code:`pushMatrix()` and :code:`popMatrix()` have been
>   replaced by a single :code:`push_matrix()` context manager that
>   cleans up after itself. [...]
> ```
>      with push_matrix():
>          translate(width / 2, height / 2)
>          point(0, 0)
> ```

In processing.py pushMatrix() can be used _either_ as a context manager() or to push with a manual pop, in the Java style.

If manual push_matrix() in p5py isn't implemented in the non-context-manager way, it looks like the issue might be that `pop_matrix()` should be dropped entirely from the api or throw an error.

**Comment by jeremydouglass** [comment] 2020-04-20 02:23
See #147

**Comment by tyagi619** [comment] 2020-04-20 03:23
i went through the code and is how pop_matrix is implemented:
```
def pop_matrix():
        push_matrix()
```
As you pointed out it needs to be removed as it seems to be redendent

**Comment by jeremydouglass** [comment] 2020-04-24 04:05
Is this true of `push()` and `pop()` in the same way? Should `pop()` be dropped from documentation, and `push()` only used with `with push():` ?

**Comment by tyagi619** [comment] 2020-04-24 06:31
Can i fix this issue?

**Comment by jeremydouglass** [comment] 2020-04-24 06:42
Hi @tyagi619 -- could you test / code review the PR that I posted? Unless you suggest a different approach?

**Comment by tyagi619** [comment] 2020-04-24 06:44
i guess i can

**Comment by jeremydouglass** [comment] 2020-04-24 06:48
Did you want to do something else instead, or your own PR?

**Comment by jeremydouglass** [comment] 2020-04-25 02:43
@tyagi619 -- would you prefer that I withdraw my PR so that you can submit your own?

**Comment by tyagi619** [comment] 2020-04-25 04:05
that would be great

**Comment by tyagi619** [comment] 2020-04-25 08:16
We can use a stack to store the transformation matrix whenever push_matrix() is called and then pop from the stack whenever pop_matrix() is called. Would it be better this way or should I just remove the pop_matrix() ?

**Comment by jeremydouglass** [comment] 2020-04-25 18:54
I _think_ just remove pop_matrix, and clean up the reference and documentation accordingly, as per:

> Processing's pushMatrix() and popMatrix() have been replaced by a single push_matrix() context manager that cleans up after itself. https://github.com/p5py/p5/blob/master/docs/guides/for-processing-users.rst

This was what I modeled in my PR and originally requested your review. 

@parsoyaarihant @abhikpal -- do you think p5 should implement both `with push_matrix(
):` AND `push_matrix() ... pop_matrix()`, the way that Processing.py does, or do you want to only support `with push_matrix():` and remove `pop_matrix()`, as described in the docs?

Note that using pop_matrix as a context manager as implemented already creates a de-facto stack -- the call stack. You can see recursively nested calls creating a matrix stack ~5-deep, here:

```
from p5 import *

def setup():
    size(400,400)
    no_loop()

def draw():
    background(255)
    translate(width/2, height/2)
    quad(width)
    no_loop()

def quad(w):
    w = w*0.8;
    if w < 5: return
    fill(255,random_uniform(255),random_uniform(255))
    rect((-w/2,-w/2),w,w)
    with push_matrix():
        translate(-w/4,-w/4);
        quad(w/2)
    with push_matrix():
        translate(w/4,-w/4);
        quad(w/2)
    with push_matrix():
        translate(-w/4,w/4);
        quad(w/2)

if __name__ == '__main__':
    run()
```

<img width="400" alt="Screen Shot 2020-04-25 at 11 53 40 AM" src="https://user-images.githubusercontent.com/798570/80288226-736a3c00-86eb-11ea-8952-d93d62ae10d2.png">

**Comment by tyagi619** [comment] 2020-04-26 09:49
Just let me know which way you would prefer and i would do it accordingly
@jeremydouglass

**Comment by jeremydouglass** [comment] 2020-04-27 14:34
Great @tyagi619 -- since we haven't heard back from @parsoyaarihant @abhikpal, I'd suggest going ahead with:

make a PR supporting `with push_matrix():` only, removing pop_matrix()

I believe this approach is consistent with their design and documentation.

**Comment by tyagi619** [comment] 2020-04-28 18:35
@jeremydouglass i will do the uodates by tomorrow

**Comment by jeremydouglass** [comment] 2020-04-30 23:40
Hi @tyagi619 -- are you still planning on opening a PR for this?

**Closed** 2020-05-03 01:19 UTC
