### ISSUE TITLE
Ubuntu can't find the p5 module.

### ISSUE THREAD

**Issue by hackingmath** [p5py/p5#59] opened 2018-08-01 07:43 UTC
**Test script:**

```python
# put your test script here
from p5 import *

```
I used your example script, copied and pasted it into IDLE in Ubuntu. The file was saved in my home folder. Where should I save these files?
I got this error:
ModuleNotFoundError: No module named 'p5'

**Expected behavior:**

Expected the module to be found

**Actual behavior**
The Module wasn't found.

It would help if I knew where the module is to point the PYTHONPATH to it. I thought this would have automatically be done by pip installing.

I had the same problem in Windows but I was able to find the p5 module but I can't find it in Ubuntu.
**Errors produced (if any):**

**p5 version:**

**Python version:** 3.7
**Operating System:**  Ubuntu

**Comment by abhikpal** [comment] 2018-08-01 16:37
How did you install p5?

**Comment by kylepollina** [comment] 2019-05-24 17:39
I am having this issue as well, only on MacOS. I installed p5 through pip using `pip install p5 --user`.
I am getting the same error, ModuleNotFoundError: No module named 'p5'

**Comment by abhikpal** [comment] 2019-05-24 19:59
Can you try running
```which pip```
and 
```which python```

This will tell us which "pip" got run when you tried installing p5py.

**Comment by kylepollina** [comment] 2019-05-25 23:34
Okay, I fixed my issue. I made sure to install p5 using pip3 since I am using python3.7. I also had to add `/Users/kyle/Library/Python/3.7/bin/` to my PATH variable. Now it works for me.

**Comment by abhikpal** [comment] 2019-05-27 12:34
I suspect @hackingmath had a similar issue with pip/pip3. I am closing this for now, as the issue is not p5py specific.

@hackingmath, if the issue was indeed different, feel free to comment here and I'll reopen this.

**Closed by abhikpal** 2019-05-27 12:34 UTC
Labels: installation
