### ISSUE TITLE
I only get a blank window on my Mac

### ISSUE THREAD

**Issue by kantel** [p5py/p5#14] opened 2017-09-29 18:20 UTC
I tried to ru p5 on my MacBook Pro with MacOS X, 10.9. and Anaconda Python 3.5.3 (x86, 64 Bit. This is my example code:

```python
from p5 import *

def setup():
    size(400, 200)
    title("Dein Titel hier …")

def draw():
    background(255, 100, 150)
    center = (width / 2, height / 2)
    fill(0)
    rect_mode("RADIUS")
    square(center, 50)

run()
```
I only get a blank window like this:

![p5whitewindow](https://user-images.githubusercontent.com/1219909/31029846-7d0c3b40-a553-11e7-99bb-6da8044f10af.png)
I tried several of the examples and get always the same result (only a blank window). And it doesn't matter if I started the sketch fom the terminal, the interpreter or within TextMate. The result was always the same.

**Comment by abhikpal** [comment] 2017-10-01 18:50
Hmmm.. interesting. I'm pretty sure this has something to do with #10. Can someone else reproduce this on their computer?

**Comment by kantel** [comment] 2017-10-01 18:58
I did a few more test and wrote an `print()`-Statement after the last line in `draw()`. The `print()`were executed. On wednesday I've sitting on a Mac with MacOS X 10.10 (and possibly with 1011). I will try to run this small progrmm there and I will publish the results (pls excuse my bad (d)english).

**Comment by abhikpal** [comment] 2017-10-01 21:56
> The print()were executed.

I'm very sure that this issue is the same as #10. Since we're seeing some output for the prints, we know that the `draw()` loop is running. However, since there is no actual output on the screen, we know that the screen isn't refreshing as it should.

> On wednesday I've sitting on a Mac with MacOS X 10.10 (and possibly with 1011)

:+1:

> I will publish the results

Can you just do that on the discussion thread for #10? I'm closing this for now, 'cause I'm pretty sure this issues and #10 are the same thing.

Thank you so much for putting time into testing this :) ...and your English is perfectly fine; don't worry.

**Closed** 2017-10-01 21:56 UTC
