### ISSUE TITLE
metadata-generation-failed

### ISSUE THREAD

**Issue by osama1998H** [p5py/p5#390] opened 2022-09-11 19:23 UTC
**Describe the bug**
Error when generating metadata on this step(Preparing metadata (pyproject.toml) did not run successfully.)

**To Reproduce**
Steps to reproduce the behavior (if applicable)

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/42488643/189545342-69a98b7c-2705-415b-92ac-00b82f40b98b.png)

**System information:**
 - p5 release (version number or latest commit): latest version
 - Python versions: 3.10 and 3.9
 - Operating system: windows 10 x64

**Additional context**

**Comment by tushar5526** [comment] 2022-09-12 05:09
Hi, can you share the steps that produced this? Did this happen while you were trying to install the library?

**Comment by osama1998H** [comment] 2022-09-12 06:04
Hi @tushar5526 
Its just one step
Pip install p5 
It's download successfully but after this throwing an error

**Comment by phildub64** [comment] 2022-09-12 15:21
I have the same issue. I upgraded everything (pip included) and always metadata error.

**Comment by tushar5526** [comment] 2022-09-12 15:29
There seems to be some installation problem with numpy. Try installing the dependencies manually, more specifically, try this.

`pip install numpy` 
`pip install p5 or build from the latest commit` in a fresh environment

**Comment by osama1998H** [comment] 2022-09-12 15:30
> There seems to be some installation problem with numpy. Try installing the dependencies manually, more specifically, try this.
> 
> `pip install numpy` `pip install p5 or build from the latest commit` in a fresh environment

I have numpy installed on my computer

**Comment by semacki2** [comment] 2022-09-14 22:48
> > I have numpy installed on my computer
> 
> Can you try installing everything in a fresh python virtual environment?

I'm experiencing the same error. 
I created a new virtual environment with python 3.8 and only ran 
`pip install p5`
and it worked without error; however, when I try to run a basic script :
![image](https://user-images.githubusercontent.com/24706242/190276246-d3713f4f-4a48-45bc-8bcd-2b1090d3b1b4.png)

I get the following runtime error:
`ModuleNotFoundError: No module named 'p5'`

**Comment by tushar5526** [comment] 2022-09-15 05:11
Hi you have to setup VS code to use the new virtual environment you have created. It's generally Ctrl + Shift + P -> Select Python interpreter -> select you  virtual environment. 

You can google as well on how to select your virtual environment in vscode. 

I will also recommend you to try the new 2D renderer skia for better performance. 

```
p5.run(renderer="skia")
```

**Comment by osama1998H** [comment] 2022-09-15 21:43
@tushar5526 
I installed release 0.7.1 and its works correctly on my laptop
but 0.8.0 not working

**Comment by ziyaointl** [comment] 2022-09-17 07:46
I was able to reproduce this issue on windows using Python 3.10 installing from pypi.

Installing directly from the latest source code resolved the numpy issue, but installation for pyopengl-accelerate was failing. I wasn't able to resolve this by tweaking the versions in the requirements.txt, so I manually downloaded wheels files and installed them using the instructions here: https://stackoverflow.com/questions/59725675/need-to-install-pyopengl-windows.

**Comment by tushar5526** [comment] 2022-09-18 10:26
> @tushar5526 I installed release 0.7.1 and its works correctly on my laptop but 0.8.0 is not working

You could try installing from the source and using python versions >= 3.7 and <= 3.9, by the time we fix it for 3.10

**Comment by tushar5526** [comment] 2022-09-20 06:42
It seems, pyopengl accelerate does not support 3.10 for Linux as of now. We would have to wait for them to fix it. If someone still wants to use python 3.10 for some reason, they could use the workaround mentioned here https://github.com/mcfletch/pyopengl/issues/74#issuecomment-1220178550, else we will recommend sticking to python versions from 3.7 to 3.9

**Comment by phildub64** [comment] 2022-09-24 08:45
For me, it doesn't work with python 3.9 and 3.10. 3.8 is ok.

**Comment by tushar5526** [comment] 2022-09-24 09:04
#398 would fix this

**Comment by tushar5526** [comment] 2022-09-29 12:05
Closing this by #398

**Closed by tushar5526** 2022-09-29 12:05 UTC
