### ISSUE TITLE
p5/ Skia in Pycharm rendering just a black screen

### ISSUE THREAD

**Issue by KnightRider3508** [p5py/p5#424] opened 2023-02-22 05:49 UTC
New to Github, p5, sorry if I missed something

**Describe the bug**
trying to use skia as the renderer however it is not drawing I added background to end of draw to circumvent bug putting it in setup. Works properly in visper but not skia see screenshots for reference.

**To Reproduce**
from p5 import *

circlex = 200

def setup():
    size(400, 300)

def draw():
    global circlex
    no_stroke()
    fill(255)
    circle(circlex, 150, 24)
    background(0)

run(renderer="skia")

**Expected behavior**
White circle drawn at 200, 150

**Screenshots**
![Screenshot (18)](https://user-images.githubusercontent.com/35079098/220533103-4d48ffc9-7a00-4c45-8fcc-77f7f9aa88ea.png)

![Screenshot (19)](https://user-images.githubusercontent.com/35079098/220533132-a0a96a3a-a9e6-46f2-aeff-a232875a7ba8.png)

**System information:**
 - p5: 0.8.2
 - Python version: 3.10.10
 - Operating system: W10

**Additional context**

**Comment by tushar5526** [comment] 2023-02-22 18:13
You are calling background(0) at the end, which basically means to set everything to black. Move this to the top in draw()

**Comment by KnightRider3508** [comment] 2023-02-22 20:45
that is originally how I had it. However that doesn't work If I just try drawing a  white BG it doesn't render it.  Size of canvas does change if I change size param.

from p5 import *


def setup():
    size(400, 300)


def draw():
    background(255)


run(renderer="skia")


![Screenshot (21)](https://user-images.githubusercontent.com/35079098/220754200-a6d8887c-2128-4e4c-91a2-3da1f0c37560.png)

**Comment by KnightRider3508** [comment] 2023-02-22 20:48
Here is a screenshot of my packages I have in my env in case something doesn't look right
![Screenshot (22)](https://user-images.githubusercontent.com/35079098/220755322-5e947adf-652c-4e20-abd1-42cc1e1b0115.png)

**Comment by KnightRider3508** [comment] 2023-02-23 21:06
Resolved by using run(renderer='skia') instead of run(renderer="skia")

**Comment by smlpt** [comment] 2023-03-05 20:22
@tushar5526 Can you reopen this issue? Because I've just run into the same problem of getting a black screen with skia.

example code:

```python
from p5 import *

def setup():
    size(640, 640)
    no_stroke()

def draw():
    background(128)
    fill(255)
    circle((width/2, height/2), 256)


run(renderer='skia')
```

P5 runs in a virtual environment with all the packages installed that come with the P5 library.

Vispy:
![image](https://user-images.githubusercontent.com/83579186/222983559-e93beb5d-e46c-433d-a392-53f0ab923814.png)
Skia:
![image](https://user-images.githubusercontent.com/83579186/222983598-85b893a3-3e48-4054-97c0-49588b75bc7a.png)

(The size disparity in window sizes seems to be a scaling issue from Windows; I dragged the P5 window onto my second monitor to take the screenshot.)

Is there something obvious I'm missing or is this maybe a bug in P5 related to skia?

**Comment by tushar5526** [comment] 2023-03-05 20:25
Hey, this is fixed by #420. Try installing git from github directly, a new release is not made yet.

**Comment by smlpt** [comment] 2023-03-05 21:38
> Hey, this is fixed by #420. Try installing git from github directly, a new release is not made yet.

Thanks for the quick answer. I tried `pip install git+https://github.com/p5py/p5.git#egg=p5` but nothing changed. Is there a specific branch that I should install?

**Comment by tushar5526** [comment] 2023-03-07 05:24
Possibly related to #425 Can you try removing `size()` function from the setup and try again?

**Comment by smlpt** [comment] 2023-03-07 08:55
Yes, this seems to work indeed. Interesting bug.

**Comment by tushar5526** [comment] 2023-03-07 15:28
> Yes, this seems to work indeed. Interesting bug.

#399 is the cause majorly

**Comment by TheGreatSquid** [comment] 2023-06-04 08:11
> Possibly related to #425 Can you try removing `size()` function from the setup and try again?
So is it not possible to have a different size canvas with the skia renderer currently?

**Comment by tushar5526** [comment] 2023-11-17 09:50
Hey folks, I finally sat down to put out a fix for this. It should be solved now. The weird behaviour is majorly due to the swapping of buffers. Tested it on my local and seems to be working fine. 

Closing the issue now :)

**Closed by tushar5526** 2023-11-17 09:50 UTC
Labels: bug, priority-high

**Comment by smlpt** [comment] 2023-11-17 12:06
Can confirm that it works on my side 👍 
Thanks a lot for your effort!
